version: '3.9'
services:
  backend:
    build: .
    image: echo-bedriftstur-backend:latest
    depends_on:
      - database
    ports:
      - '5000:5000'
    links:
      - database
    environment:
      API_KEY_1: test
      DATABASE_HOST: database

  database:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'secretpassword'
      POSTGRES_USER: 'postgres'
      POSRGRES_DB: 'postgres'
