version: '3.9'
services:
  database:
    image: postgres:13
    restart: always
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: schmassord
      POSTGRES_USER: postgres
      POSRGRES_DB: postgres
  backend:
    build: .
    image: echo-bedriftstur-backend:latest
    depends_on:
      - database
    ports:
      - '8080:8080'
    environment:
      POSTGRES_PASSWORD: schmassord
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: 0.0.0.0
      API_KEY_1: test
      DEVELOPMENT: jadda
